### PR TITLE
Fix gtest for gcc-4.8

### PR DESCRIPTION
**Pull request by fargies**
@biojppm this is not ready just wanted to discuss before making further changes.

Going this route we'll have two `gcc-4.8.hpp` to maintain (that must be identical):
- one here for gtest that makes `cmake` repo standalone
- one in c4core and bundled with it

As an alternative solution, since only rapidyaml (from the repos I know) uses gtest, the patch + include can be made in rapidyaml, referencing the file from c4core (if it exists).

Also I wonder how a symlink in c4core `src/c4/compat/gcc-4.8.hpp -> cmake/compat/gcc-4.8.hpp` would behave on windows.
(copy or symlink can probably be made dynamically in CMake)

That's really up to you.

### CODE REVIEW

**Comment by biojppm** [comment]
@fargies thanks for sticking and apologies for the late reply. I just started a new contract and time has been limited.

I don't get your point regarding the need for the two header files. Can you elaborate why two header files would be needed?

The way I see it is like this: cmake is a submodule of c4core, so c4core can rely on the existing header inside cmake, injecting or adding its include dir as (or if) needed (and also amalgamating correctly). That's pretty much it. So no need to duplicate the header in c4core. From there, it's just a matter of proper specification of the public interface of c4core. Then any client library of c4core will inherit the proper settings.

**Comment by biojppm** [comment]
For me, as it is, this MR is good to go and ready to merge. Then unless I'm missing something c4core only needs the call to  `target_compile_options(....PUBLIC....)` pointing at the compat header inside cmake.

**Comment by biojppm** [comment]
Also, linking to the original PR in biojppm/rapidyaml#217 for cross-referencing.

**Comment by fargies** [comment]
Hello,

I've slightly updated the PR:
- file still gets included from `compiler.hpp`, adding proper directory in path.
- in cmake build-system this additional include_dir should propagate, which is sufficient for rapidyaml (and/or client apps)
- in amalgamate file is injected (as before)
- with install rules file is installed (in c4 dir to be found by compiler.hpp)

I'll create PR for c4core and rapidyaml

**Comment by biojppm** [comment]
Great stuff! Thanks

**Pull request merged**
